const {
  PORT,
  MONGODB_URI,
  NODE_ENV,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  WORKER_CONCURRENCY,
  JOB_IMPORT_CRON_TIME,
  JOB_BATCH_SIZE,
  LOG_LEVEL,
} = process.env;

module.exports = {
  PORT,
  MONGODB_URI,
  NODE_ENV,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  WORKER_CONCURRENCY,
  JOB_IMPORT_CRON_TIME,
  JOB_BATCH_SIZE,
  LOG_LEVEL,
};
